# .github/workflows/profile-summary-cards.yml
name: Profile Summary Cards
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: himanshusaini11
          BRANCH_NAME: main
          UTC_OFFSET: 0
          AUTO_PUSH: true